### ISSUE TITLE
BEGIN

### ISSUE THREAD

**Issue by brendangregg** [iovisor/ply#14]
Some way to run code (eg, printf()s) at the start of the program. Useful for printing headings. awk has BEGIN, which is even used in the ply source already:

```
[...]
autom4te.cache/output.1:BEGIN {
config.status:ac_cs_awk_cr=`$AWK 'BEGIN { print "a\rb" }' </dev/null 2>/dev/null`
config.status:echo 'BEGIN {' >"$ac_tmp/subs1.awk" &&
config.status:BEGIN {
configure:ac_cs_awk_cr=`$AWK 'BEGIN { print "a\rb" }' </dev/null 2>/dev/null`
configure:echo 'BEGIN {' >"$ac_tmp/subs1.awk" &&
configure:BEGIN {
Makefile:  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
Makefile:  BEGIN { nonempty = 0; } \
Makefile.in:  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
Makefile.in:  BEGIN { nonempty = 0; } \
[...]
```

**Comment by wkz** [comment]
Yes, I think it would be great to have a `ply` provider for things like `ply:BEGIN`, `ply:END` and `ply:every:1s`.

The hard thing about this is that there is no context to run the resulting bpf-program in, so I'll have to implement a ply-script interpreter.

**Comment by brendangregg** [comment]
Ah, right. For now it could be for printf statements only. An interpreter could detect the BEGIN, do the printf's, then remove the BEGIN code from the program and carry on with BPF as normal.

**Comment by mlen** [comment]
> The hard thing about this is that there is no context to run the resulting bpf-program in, so I'll have to implement a ply-script interpreter.

Maybe adding uprobe support would make it cleaner? Basically ply would attach uprobe to a bunch of dummy calls that'd trigger bpf execution for ply provider

**Comment by wkz** [comment]
@mlen yeah i guess you could attach them to an internal function in `ply` that would only be invoked once for `BEGIN` and once for `END`.
