### ISSUE TITLE
quantize histogram output as an ASCII diagram

### ISSUE THREAD

**Issue by brendangregg** [iovisor/ply#2]
```
# ply -c 'kprobe:SyS_read { $bytes.quantize(arg(2)); }'
1 probe active
^Cde-activating probes

$bytes:
[   0,    1]	     698
[  64,  128)	      31
[ 128,  256)	       2
[ 512,   1k)	     109
[  1k,   2k)	      18
[  4k,   8k)	      28
[ 16k,  32k)	       3
```

This is a good terse output for power-of-2 histograms, however, I think it should be optional, and the default should be something more easily readable, like:

```
      value          : count     distribution
       0 -> 1        : 3        |                                      |
       2 -> 3        : 0        |                                      |
       4 -> 7        : 211      |**********                            |
       8 -> 15       : 0        |                                      |
      16 -> 31       : 0        |                                      |
      32 -> 63       : 0        |                                      |
      64 -> 127      : 1        |                                      |
     128 -> 255      : 800      |**************************************|
```

Note that zero rows are included, as well as an ASCII distribution. (The ASCII distribution would make less sense if the zero rows were elided). Optionally, the heading "value" could be changed. Eg, in this case, to "bytes".

This could be accomplished a number of ways. Here's one suggestion:

```
# emits the raw output (as it does today):
ply -c 'kprobe:SyS_read { $bytes.quantize(arg(2), raw=true); }' 

# emits the sample output above:
ply -c 'kprobe:SyS_read { $bytes.quantize(arg(2)); }'

# emits the sample output, but with the value column renamed:
ply -c 'kprobe:SyS_read { $bytes.quantize(arg(2), value="bytes"); }'
```

I've opted against just adding optional arguments to quantize (eg, "quantize(arg(2), true, "bytes"). I think positional arguments like those should be for the common use cases. In cases where the argument would be uncommonly used, a key=value approach may be easier for users to learn and remember, since it self documents.

**Comment by brendangregg** [comment]
Actually, "bytes" is already in the program as "$bytes", so these could just be:

```
# emits the raw output (as it does today):
ply -c 'kprobe:SyS_read { $bytes.quantize(arg(2), raw=true); }' 

# emits the sample output (with the value column named "bytes"):
ply -c 'kprobe:SyS_read { $bytes.quantize(arg(2)); }'
```

**Comment by wkz** [comment]
Yes I agree, the ASCII-histogram is nice. I will definitely implement something like this.

About the range output, I was trying to go for something that would be unambiguous, yet easy to read even as numbers get large. I thought the open/closed range notation would be familiar to most people. Is it hard on the eyes? Or was it mostly the ASCII-output and intermediate zero-buckets you where after?

**Comment by brendangregg** [comment]
I like the condensed output, and open/close range notation. I think it should stay as a raw mode. But it feels a bit like SystemTap's raw statistical output, and has me reaching for the human readable version with an ASCII chart.

**Comment by wkz** [comment]
I just pushed a draft of this feature as wkz/quantize. I'll add an ASCII fall-back later, but it was fun to play with UTF-8 block characters :smile: 

I was also thinking about the "raw-mode", I think that it should be a global option when running ply. If you want raw output, you probably want it on all maps. It also means a user can run the same script in either mode, depending on the situation.

**Comment by brendangregg** [comment]
Wow, those bars are nice:

```Shell
root@bgregg-build-i-a353d777:/mnt/src/ply# ply -c 'kprobe:SyS_read { $bytes.quantize(arg(2)); }'
1 probe active
^Cde-activating probes

$bytes:

	[   0,    1]	     698 ┤████████████▍   │
	[   2,    4)	       0 ┤                │
	[   4,    8)	       0 ┤                │
	[   8,   16)	       0 ┤                │
	[  16,   32)	       0 ┤                │
	[  32,   64)	       0 ┤                │
	[  64,  128)	      31 ┤▌               │
	[ 128,  256)	       2 ┤                │
	[ 256,  512)	       0 ┤                │
	[ 512,   1k)	     111 ┤██              │
	[  1k,   2k)	      30 ┤▌               │
	[  2k,   4k)	       0 ┤                │
	[  4k,   8k)	      28 ┤▌               │
	[  8k,  16k)	       0 ┤                │
	[ 16k,  32k)	       4 ┤▏               │
```

Although I bet there'll be situations (terminals, wordprocessors) where they aren't supported. Could there be a mode to do plain ASCII instead? like # or @ characters?

The x-width of the histogram could be doubled. (And still be well within 80 chars.)

Yes, raw-mode can be a global option, affecting all maps. Plus you can have a raw-ascii-mode for the plain ASCII histograms.

**Comment by brendangregg** [comment]
PS, I'd delete the extra new line after $bytes. Imagine we print a bunch of these, or have a histogram for each key. Oh, you already did that if I do multiple keys:

```
# ply -c 'kprobe:SyS_read { $bytes[execname].quantize(arg(2)); }'
1 probe active
^Cde-activating probes

$bytes:
chmod           
	[ 512,   1k)	      10 ┤████████████████│
chown           
	[ 512,   1k)	      40 ┤███████████▍    │
	[  1k,   2k)	       0 ┤                │
	[  2k,   4k)	       0 ┤                │
	[  4k,   8k)	      16 ┤████▋           │
mkdir           
	[ 512,   1k)	      32 ┤██████████▋     │
	[  1k,   2k)	      16 ┤█████▍          │
readproctitle   
	[   0,    1]	    1340 ┤████████████████│
run             
	[  64,  128)	      62 ┤███▉            │
	[ 128,  256)	       4 ┤▎               │
	[ 256,  512)	       0 ┤                │
	[ 512,   1k)	     138 ┤████████▌       │
	[  1k,   2k)	      17 ┤█               │
	[  2k,   4k)	       0 ┤                │
	[  4k,   8k)	      38 ┤██▍             │
sshd            
	[ 16k,  32k)	       4 ┤████████████████│
supervise       
	[   0,    1]	      60 ┤████████████████│
```

Nice. Ok, forget this comment. :)

**Comment by brendangregg** [comment]
as part of the integration, I'd update README.md and the landing page. Actually, the above example

```ply -c 'kprobe:SyS_read { $bytes[execname].quantize(arg(2)); }'```

makes for a good example (and fast to instrument, too). Only catch is it's requested bytes, not returned bytes (need the kretprobe).

**Comment by wkz** [comment]
Ok, I added the ASCII fallback. It's a separate option right now, I'm thinking it should maybe be combined with the raw option into something like `-P raw|plain|pretty` instead. But at least you can get to it for now if there is a need for it.

Also tuned the output to show negative numbers, put zero in a separate bucket from 1, print small numbers as closed ranges.

Available at wkz/quantize. Comments?

Also on that branch, kretprobes :smile: See #4

**Comment by brendangregg** [comment]
Tested, works for me. -A is fine for now, and as you say, we could make that a -P later. I'd integrate wkz/quantize now.

How come some ranges end in ']' and some in ')'?:

```
# ply -A -c 'kretprobe:SyS_read { $bytes.quantize(retval); }'
1 probe active
^Cde-activating probes

$bytes:
	         < 0	      66 |#                               |
	           0	      61 |#                               |
	           1	    2245 |########################        |
	[   2,    3]	       8 |                                |
	[   4,    7]	      12 |                                |
	[   8,   15]	       0 |                                |
	[  16,   31]	       2 |                                |
	[  32,   63]	       4 |                                |
	[  64,  127]	     108 |#                               |
	[ 128,  255]	       3 |                                |
	[ 256,  511]	      59 |#                               |
	[ 512,   1k)	     358 |####                            |
	[  1k,   2k)	      32 |                                |
	[  2k,   4k)	       1 |                                |
```

**Comment by wkz** [comment]
That's because the smaller intervals are written as right-closed intervals, while the larger ones are written as right-open. I just think `[ 32k,  64k)` is more clear than `[ 32k, 64k - 1]` or `[32768, 65535]`

It follows the ISO interval notation:
https://en.wikipedia.org/wiki/Interval_(mathematics)

**Comment by brendangregg** [comment]
ok, thanks.
