### ISSUE TITLE
what's the difference with ktap 

### ISSUE THREAD

**Issue by carltraveler** [iovisor/ply#22]
seems the same. like both lightweight and the samilar syntax

**Comment by joshbaptiste** [comment]
Ktap didn't use the eBPF framework and required a kernel module from what I remember. I think they abandoned development until eBPF developed  further to make it compatible with eBPF.

**Comment by wkz** [comment]
I would say that they are similar in spirit, but differ in the technology used. The ktap project installs their own VM to run their probes in, whereas ply uses the mainline BPF facilities. ktap is also much more mature than ply.
