### ISSUE TITLE
kretprobe support

### ISSUE THREAD

**Issue by brendangregg** [iovisor/ply#4]
arg(0) could be the return value

**Comment by wkz** [comment]
Yes, this is high on my list of things todo.

I'm thinking something like:

    kprobe:SyS_open:return / retval / {
        $open_errors[execname, pid].count()
    }

**Comment by brendangregg** [comment]
but that's inventing a new field. You already have a field, "kprobe", to identify the probe type, so may as well use it for the other probe types too: kretprobe, uprobe, uretprobe, and later on tracepoints and USDT.

**Comment by wkz** [comment]
Well i see `kprobe` as the provider in both cases, they use the same sysfs control interface for example. What follows after `kprobe:` is the "argv" for the provider to parse. I imagine these variants:

`kprobe:SyS_open`
`kprobe:SyS_open:+0x24`
`kprobe:SyS_open:return`

uprobes might look something like:

`uprobe:bash:readline`
`uprobe:bash:readline:+0xc`
`uprobe:bash:readline:return`

**Comment by brendangregg** [comment]
perf did this with a "%return" suffix, I think, I forget the exact syntax, which is also my point.

It really is a kretprobe. You can do an internet search for that term.

It's not a big difference between the two, but I think :return is inventing new syntax when we don't need to: we already have the first field to identify the probe type, and it really is a different probe type. The arguments are different too. Calling it kretprobe to start with makes it clear that it's a different probe, and it can have different arguments.

**Comment by brendangregg** [comment]
Plus we already have a standard way to specify offsets: readline+0xc. So:

```
kprobe:SyS_open+0x24
uprobe:bash:readline+0xc
```

**Comment by wkz** [comment]
Yeah I know they are not the same, I just thought it made sense to present them that way.

But you make fair point about the semantics of built-ins being different. `retval` is nonsense in `kprobe` and `arg(N)` is sourced from `pt_regs` which are likely clobbered in a `kretprobe`.

Ok, agreed. So something like this then:

    kretprobe:SyS_open / retval / {
        $open_errors[execname, pid].count()
    }

On a side-note: I've been thinking that it might be nice to have shorter aliases for providers when writing probes on the command line for example. Similar to the input to the `k`/`u``probe_events` files.

`ply -c k:SyS_open'{ $opens[execname].count() }'`
`ply -c kr:SyS_open'/ retval / { $errs[execname, pid].count() }'`

**Comment by brendangregg** [comment]
There's already shortcuts like these: 'p' for kprobes, and 'r' for kretprobes. From Documentation/trace/kprobetrace.txt:

```
Synopsis of kprobe_events
-------------------------
  p[:[GRP/]EVENT] [MOD:]SYM[+offs]|MEMADDR [FETCHARGS]  : Set a probe
  r[:[GRP/]EVENT] [MOD:]SYM[+0] [FETCHARGS]             : Set a return probe
[...]
  echo 'p:myprobe do_sys_open dfd=%ax filename=%dx flags=%cx mode=+4($stack)' > /sys/kernel/debug/tracing/kprobe_events
[...]
  echo 'r:myretprobe do_sys_open $retval' >> /sys/kernel/debug/tracing/kprobe_events
```

I used them in my kprobe tool from perf-events. But not everyone liked or could remember these shortcuts.

I'd revisit shortcuts later if there's consensus, and do kprobe & kretprobe for now.

**Comment by wkz** [comment]
Yes, that's what I meant by the `k`/`u``probe_events` files.

However, there's going to be a namespace issue if you simply use `p`/`r`, since these are used by uprobes as well. Maybe `kp`/`kr` and `up`/`ur`? But yes, let's see if there's a need first.

**Comment by wkz** [comment]
This has been added to wkz/quantize.

I added a function called `retval` which does what you'd expect.

At the moment, there is no filtering of available functions so `arg` is available on kretprobes, `retval` on kprobes and so on. It won't blow up or anything, just give you a (probably) clobbered argument.

Have to think about if they should be filtered out completely, generate a warning or something else. But with sane input scripts, it should do the Right Thing (:tm:).

**Comment by brendangregg** [comment]
Thanks, it works. Right, I can use arg/retval in the wrong places, and we can add sanity checking later on.

We could use the kp/kr/up/ur shortcuts, but I'm not sure such shortcuts were that liked with raw kprobes either. I'd consider sticking with kprobe/kretprobe/uprobe/uretprobe for now, but can add shortcuts later.
