### ISSUE TITLE
build ply for arm64 target

### ISSUE THREAD

**Issue by maindoor** [iovisor/ply#45]
Hi,
I'm trying to build ply for arm64 target but somehow I'm unable to do it:
I used configure like this:
./configure --target=arm64 --with-kerneldir=/home/kedaru/proj/base/linux/

But I still get x86_64 ply file after a make. How do I compile ply executable for arm64 target ?

Thanks.

**Comment by wkz** [comment]
Answered in https://github.com/wkz/ply/issues/18
