### ISSUE TITLE
Question: clear up map?

### ISSUE THREAD

**Issue by Leo-Yan** [iovisor/ply#51]
Hi there,

Before we can clear map with assignment 'nil', seems now the latest code base doesn't support 'nil' anymore.  So e.g. below program cannot work.

~~~
kprobe:kmem_cache_alloc_node {                
        s[cpu,kpid] = stack();                
}                                             
                                              
kretprobe:kmem_cache_alloc_node {             
        @[retval] = s[cpu,kpid];              
        s[cpu,kpid] = nil;                    
}                                             
                                              
kprobe:kmem_cache_free {                      
        @[arg1] = nil;                        
}                                             
~~~

If I change 'nil' to 0, the program can run successfully.  But the assignment for the sentence "@[retval] = s[cpu,kpid]" also cannot work as expected, I observe the result as below:

{ -281474254472384 }: <STACKID0>
{ -281474254472000 }: <STACKID0>
{ -281474231713792 }: <STACKID0>
{ -281474177160960 }: <STACKID0>
{ -281474148187360 }: <STACKID0>
{ -281474147794048 }: <STACKID0>
{ -281474147622912 }: <STACKID0>
{ -281474132892352 }: <STACKID0>
{ -281474132891456 }: <STACKID0>
{ -281474132887872 }: <STACKID0>
{ -281474132887424 }: <STACKID0>
{ -281474132886528 }: <STACKID0>

Thanks for the suggestion!

**Comment by wkz** [comment]
You're quite right. In version 2 the syntax changed to `delete map[key]`, but I have forgotten to update the manual. I assume you're looking to track where live objects where allocated from? Here is a script that should get the job done:

```
k:kmem_cache_alloc_node {
	from[cpu,kpid] = stack();
}

kr:kmem_cache_alloc_node {
	if (from[cpu, kpid]) {
		live[retval] = from[cpu,kpid];
		delete from[cpu,kpid];
	}
}

k:kmem_cache_free {
	delete live[arg1];
}
```

**Comment by Leo-Yan** [comment]
Thank you for the detailed explanation, I verified at my side, the new script works pretty well!
