### ISSUE TITLE
How to specify correct kernel version?

### ISSUE THREAD

**Issue by tiger20081015** [iovisor/ply#53]
Hi, I failed to run kprobe command in ply due to the KERNEL_VERSION_CODE checking failed. The kernel image version code actually is 265829, but the ply version printed out is 200960. How can I include the correct version.h file in ply configure command? Currently the configuration command I use is "./configure --host=aarch64-linux-gnu --prefix=/home/data/bpf/ply/install CPPFLAGS="-I /home/data/stpu/kernel/linux/include/uapi -I /home/data/stpu/kernel/linux/include/". Thanks.

**Comment by wkz** [comment]
My guess is that you're getting `linux/version.h` from your toolchain.

Things to try out:

1. Make sure that `linux/version.h` is actually generated in your tree. Typically you'd want to `-I` the directory to which you have run `make headers_install`, not the source tree.
2. Build with `V=1` to see if I've messed up the Makefile somehow so that `CPPFLAGS` isn't being used correctly.

**Comment by tiger20081015** [comment]
wkz, thanks for your apply. 
I used "make headers_install" to generate version.h under SRCTREE/usr/include/linux.  Then use configuration "./configure --host=aarch64-linux-gnu --prefix=/home/data/bpf/ply/install CPPFLAGS="-I /home/data/stpu/kernel/linux/usr/include -I /home/data/stpu/kernel/linux/include/uapi -I /home/data/stpu/kernel/linux/include/"" to build ply. The command "ply -v" shows now the ply version complies with the kernel image. But when I run "ply 'kretprobe:vfs_read { printf("fswu %s %d\n", comm, retval); }'", it prints out "error: unable to create map 'stdbuf', errno:38", which never met before.

Current I use below workaround:
1. under SRCTREE, run "make include/generated/uapi/linux/version.h";
2. ln -s SRCTREE/include/generated/uapi/linux/version.h SRCTREE/include/linux/version.h
3. Remove "-I /home/data/stpu/kernel/linux/usr/include" from my previous configuration.

**Comment by wkz** [comment]
Since you're running ply in #54, I assume you managed to build it. Closing this.
