### ISSUE TITLE
Segmentation fault in ply_fparse due to null pointer dereference in node_append

### ISSUE THREAD

**Issue by jvijtiuk** [iovisor/ply#57]
Hello,

the file attached below causes a segmentation fault. It was found by fuzzing ply_fparse and can be reproduced by running ply with the file as an argument.
[nullptr.zip](https://github.com/iovisor/ply/files/4885746/nullptr.zip)

The issue seems to be in node_append in node.c:263. When the file is parsed, tail is NULL, so tail->prev is a NULL pointer dereference. Returning NULL if tail is NULL seems to fix the issue and ply then successfully reports an error with the following output:

```
[root@fuzz ply]# ./src/ply/.libs/ply ./nullptr
1: error: syntax error, unexpected IDENT, expecting ';'
ERR:-22
```

Regards,
Juraj

**Comment by wkz** [comment]
This does not blow up on my system. I assume you're on x86_64?

My output is:

    1: error: syntax error, unexpected ')'
    ERR:-22

**Comment by jvijtiuk** [comment]
Yes, I am on x86_64.
Here is the valgrind output when I run ply with the file:
```
[root@fuzz ply]# valgrind ./src/ply/.libs/ply nullptr
==4321== Memcheck, a memory error detector
==4321== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4321== Using Valgrind-3.16.0.GIT and LibVEX; rerun with -h for copyright info
==4321== Command: ./src/ply/.libs/ply nullptr
==4321==
==4321== Invalid write of size 8
==4321==    at 0x485E1B1: node_append (node.c:263)
==4321==    by 0x4859DB3: yyparse (grammar.y:123)
==4321==    by 0x4860110: ply_fparse (libply.c:148)
==4321==    by 0x1093AF: main (ply.c:249)
==4321==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==4321==
==4321==
==4321== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==4321==  Access not within mapped region at address 0x8
==4321==    at 0x485E1B1: node_append (node.c:263)
==4321==    by 0x4859DB3: yyparse (grammar.y:123)
==4321==    by 0x4860110: ply_fparse (libply.c:148)
==4321==    by 0x1093AF: main (ply.c:249)
==4321==  If you believe this happened as a result of a stack
==4321==  overflow in your program's main thread (unlikely but
==4321==  possible), you can try to increase the size of the
==4321==  main thread stack using the --main-stacksize= flag.
==4321==  The main thread stack size used in this run was 8388608.
==4321==
==4321== HEAP SUMMARY:
==4321==     in use at exit: 22,095 bytes in 22 blocks
==4321==   total heap usage: 53 allocs, 31 frees, 25,680 bytes allocated
==4321==
==4321== LEAK SUMMARY:
==4321==    definitely lost: 0 bytes in 0 blocks
==4321==    indirectly lost: 0 bytes in 0 blocks
==4321==      possibly lost: 0 bytes in 0 blocks
==4321==    still reachable: 22,095 bytes in 22 blocks
==4321==         suppressed: 0 bytes in 0 blocks
==4321== Rerun with --leak-check=full to see details of leaked memory
==4321==
==4321== For lists of detected and suppressed errors, rerun with: -s
==4321== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

I'll look into what part of the file seems to be crashing, and will remove the fix on my version of ply to try and get more variations of the crash with the fuzzer.
If there is anything else I can provide, please let me know.

**Comment by jvijtiuk** [comment]
Sorry for the delay, I was busy with some other things.

Could you please try if any of the following files reproduce the crash?

[nullptr_crashes.zip](https://github.com/iovisor/ply/files/5014575/nullptr_crashes.zip)

Those were all found by fuzzing and cause the same issue described above on my systems. I've tested on x86_64 Arch Linux and Debian, and on ARM32 Debian running virtualized with the QEMU virt board.
