### ISSUE TITLE
Does ply work on kernel 4.8?

### ISSUE THREAD

**Issue by chneukirchen** [iovisor/ply#6]
I built ply cfc56c7 against Linux 4.8.4_1, but it doesn't seem to like the bpf code:

```
% sudo strace ./src/ply -c 'kprobe:SyS_open { $opens.count() }'
...
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_HASH, key_size=8, value_size=8, max_entries=512}, 48) = 3
open("/sys/kernel/debug/tracing/kprobe_events", O_RDWR|O_CREAT|O_APPEND, 0666) = 4
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=29, insns=0x1315558, license="GPL", log_level=1, log_size=131072, log_buf=0x611780, kern_version=262415}, 48) = -1 EINVAL (Invalid argument)
```

**Comment by wkz** [comment]
Looking at the `kern_version` in the `bpf` syscall, it looks like `ply` has been built against kernel headers from version 4.1.15. The kernel is quite picky about the bpf program being built against the **exact** version of the kernel you're running.

Have you upgraded the `linux-headers` package (or similar) from your distro?

**Comment by chneukirchen** [comment]
Oh, I see. My distro doesn't have newer kernel headers than 4.1, but I passed `---with-kerneldir`. 
I rebuilt it cleanly and now it used `kern_version=264196` and the example works.

This is a bit annoying to package it, tho...

**Comment by wkz** [comment]
Amen, I agree completely. I toyed with the idea of just calling `uname(2)` and constructing the version from that. That seemed to counteract the intention of the field though.

What would you suggest?

**Comment by chneukirchen** [comment]
The only check seems to be that the version matches exactly the kernel version... since you compile the eBPF code yourself anyways, it should be ok to fake that field if you think the bytecode will run on the current kernel.

(Contrast to a static BPF program generated by macros...)

**Comment by wkz** [comment]
So it turns out that some distros set the patch version is such a way that does not correspond with the output of `uname(2)`. Conclusion: For now at least, you will have to re-build `ply` when you update your kernel.
