### ISSUE TITLE
arm64  kernel4.19  kprobe & kretprobe all failed.   why ?

### ISSUE THREAD

**Issue by chenzhbao629** [iovisor/ply#61]
ply 'kprobe:do_sys_open { printf("opened:%s\n", str(arg1));}' 
[1] 41739
error: unable to load kprobe:do_sys_open, errno:22
error: no output from kernel bpf verifier, retry with debugging enabled
ERR:-22

ply 'kprobe:watchdog_timer_fn { @[stack] = count(); }'
error: unable to load kprobe:watchdog_timer_fn, errno:22
error: no output from kernel bpf verifier, retry with debugging enabled
ERR:-22

**Comment by wkz** [comment]
Could you retry with debugging enabled? (`-d`)

**Comment by chenzhbao629** [comment]
Sorry that my problem, forget to install header file.

**Comment by yeshen007** [comment]
> Sorry that my problem, forget to install header file.

i counter with the same problem,what header file to needed to be installed,and how to install

**Comment by woniu2014** [comment]
> 
please, how to install the kernel header file?

**Comment by woniu2014** [comment]
> Sorry that my problem, forget to install header file.

please, how to install the kernel header file?

**Comment by wkz** [comment]
That very much depends on what type of build environment you're in.

Ideally, your toolchain should be built against a recent enough kernel that you wouldn't need to care about this at all. You can find this version in `usr/include/linux/version.h` of your toolchain's sysroot.

In lieu of that, if you are building your kernel from sources, you can invoke the `headers_install` target to install the headers to a location that is accessible from your toolchain. See the kernel docs: https://www.kernel.org/doc/Documentation/kbuild/headers_install.txt

**Comment by woniu2014** [comment]
> 

It can compile successfully，but use ply error:
ply 'kprobe:do_sys_open { printf("opened:%s\n", str(arg1));}'
[1] 41739
error: unable to load kprobe:do_sys_open, errno:22
error: no output from kernel bpf verifier, retry with debugging enabled
ERR:-22
I use buildroot compile it

**Comment by woniu2014** [comment]
It can compile successfully，but use ply error:
 ply 'kprobe:do_sys_open { printf("opened:%s\n", str(arg1));}'
 [1] 41739
 error: unable to load kprobe:do_sys_open, errno:22
 error: no output from kernel bpf verifier, retry with debugging enabled
 ERR:-22
 I use buildroot compile it.
env:
gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu
kernel: version 4.14

CONFIG_KPROBES=y CONFIG_HAVE_DYNAMIC_FTRACE=y CONFIG_HAVE_DYNAMIC_FTRACE_WITH_REGS=y CONFIG_HAVE_FTRACE_MCOUNT_RECORD=y CONFIG_FTRACE=y CONFIG_DYNAMIC_FTRACE=y CONFIG_BPF=y CONFIG_BPF_SYSCALL=y
what do I need for it?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iovisor/ply"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iovisor/ply] arm64  kernel4.19  kprobe &amp; kretprobe all failed.   why ? (#61)





 
That very much depends on what type of build environment you're in.
 
Ideally, your toolchain should be built against a recent enough kernel that you wouldn't need to care about this at all. You can find this version in usr/include/linux/version.h of your toolchain's sysroot.
 
In lieu of that, if you are building your kernel from sources, you can invoke the headers_install target to install the headers to a location that is accessible from your toolchain. See the kernel docs: https://www.kernel.org/doc/Documentation/kbuild/headers_install.txt

**Comment by ydong08** [comment]
same issue happened in arm embedded device, it is appreciated to hear any suggestions.
i installed kernel headers in /usr/include, however, it does not work.

debug as follows:
```
# ply -d 'kprobe:dev_queue_xmit { @[stack] = count(); }'
debug: ir_bpf_generate: v0 -> r2
debug: unlimited memlock
error: unable to load kprobe:dev_queue_xmit, errno:22
error: output from kernel bpf verifier:
0: (bf) r2 = r1
1: (62) *(u32 *)(r10 -4) = 0
2: (bf) r1 = r2
3: (18) r2 = 0xe3a46000
5: (b4) w3 = 0
6: (85) call bpf_get_stackid#27
7: (63) *(u32 *)(r10 -8) = r0
8: (18) r1 = 0xd4b2b000
10: (bf) r2 = r10
11: (07) r2 += -8
12: (85) call bpf_map_lookup_elem#1
13: (15) if r0 == 0x0 goto pc+6
 R0=map_value(id=0,off=0,ks=4,vs=4,imm=0) R10=fp0 fp-8=mmmmmmmm
14: (bf) r1 = r10
15: (07) r1 += -12
16: (b4) w2 = 4
17: (bc) w3 = w0
18: (85) call unknown#113
invalid func unknown#113
processed 17 insns (limit 1000000) max_states_per_insn 0 total_states 1 peak_states 1 mark_read 1

ERR:-22
# 
# ply --version
ply 2.3.0-9-g1b57943 (linux-version:328759~5.4.55)
```

**Comment by HaoJin1994** [comment]
> same issue happened in arm embedded device, it is appreciated to hear any suggestions. i installed kernel headers in /usr/include, however, it does not work.
> 
> debug as follows:
> 
> ```
> # ply -d 'kprobe:dev_queue_xmit { @[stack] = count(); }'
> debug: ir_bpf_generate: v0 -> r2
> debug: unlimited memlock
> error: unable to load kprobe:dev_queue_xmit, errno:22
> error: output from kernel bpf verifier:
> 0: (bf) r2 = r1
> 1: (62) *(u32 *)(r10 -4) = 0
> 2: (bf) r1 = r2
> 3: (18) r2 = 0xe3a46000
> 5: (b4) w3 = 0
> 6: (85) call bpf_get_stackid#27
> 7: (63) *(u32 *)(r10 -8) = r0
> 8: (18) r1 = 0xd4b2b000
> 10: (bf) r2 = r10
> 11: (07) r2 += -8
> 12: (85) call bpf_map_lookup_elem#1
> 13: (15) if r0 == 0x0 goto pc+6
>  R0=map_value(id=0,off=0,ks=4,vs=4,imm=0) R10=fp0 fp-8=mmmmmmmm
> 14: (bf) r1 = r10
> 15: (07) r1 += -12
> 16: (b4) w2 = 4
> 17: (bc) w3 = w0
> 18: (85) call unknown#113
> invalid func unknown#113
> processed 17 insns (limit 1000000) max_states_per_insn 0 total_states 1 peak_states 1 mark_read 1
> 
> ERR:-22
> # 
> # ply --version
> ply 2.3.0-9-g1b57943 (linux-version:328759~5.4.55)
> ```

Do you fixed this problem?
