### ISSUE TITLE
how can i get a variable value in function with kprobe.

### ISSUE THREAD

**Issue by chenzhbao629** [iovisor/ply#62]
kernel version :5.7 
I want to get variable  ’duration‘ value in watchdog_timer_fn,  how i should do ?

such as:
**ply 'kprobe:watchdog_timer_fn+ offset {xxxxx}'**

Can you provide a full command for me ? 

Thanks.

**Comment by wkz** [comment]
There is no support for getting that kind of information automatically yet. You'll have to look at the generated instructions and figure out which register holds the variable at that location. You can then get to it via something like `regs->x7`.

**Comment by chenzhbao629** [comment]
Thanks.
 Bye the way,  why ebpf does not support get local variable in function ?

**Comment by wkz** [comment]
eBPF is just an instruction set, it has no concept of types or variables, it's all just registers and memory.

To support what you're looking for, ply would have to consume some type of debug information (e.g. BTF, CTF or DWARF) and generate the corresponding eBPF instructions to fetch the data.

This is certainly something I want to do, but it is not there yet.
