### ISSUE TITLE
Can I use it on the board through cross compilation?

### ISSUE THREAD

**Issue by william-ye999** [iovisor/ply#65]
I use the following instructions to compile the installation and then copy the files in the build directory to the board.
```bash
./autogen.sh
./configure --host=aarch64-linux-gnu --prefix=~/build
make
make install
```
After the files in the lib directory are copied to the /lib64 directory of the development board, I try to run ply in sbin directory. However, the following error message is displayed. Is the cross compilation chain incorrect?
```bash
ply: line 3: syntax error: unexpected "("
```

**Comment by wkz** [comment]
The build sequence looks OK.

I will stick my neck out and say that this is an issue in your environment, not with ply. I build for `aarch64` all the time, both under Buildroot and in ply's own test system (`test/Makefile`).
