### ISSUE TITLE
 use the kprobe provider to obtain a member variable of the input parameter

### ISSUE THREAD

**Issue by wanlon** [iovisor/ply#88]
hi, if I want to use the kprobe provider to obtain a member variable of the input parameter, how should I implement it

**Comment by wkz** [comment]
No way of doing that yet I'm afraid. To support that, ply must have the ability to read BTF or DWARF to figure out the types. At the moment, all arguments are just `unsigned long`s.

In a pinch, you can still get to the data with `mem(argX + offs, size)`, but you have to figure out `offs` and `size` externally.
